name: Main

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * MON'

env:
  PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PACKAGES_USERNAME: ${{ github.actor }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:

  build-publish-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image, test it, push to registry
        run: ./pipe_build_up_test.sh